import React from 'react';
import { motion } from 'framer-motion';

const UserPreviewTable = ({ users, userType, onConfirm, onCancel }) => {
  if (!users || users.length === 0) {
    return (
      <div className="text-center text-gray-500 mt-8">
        No {userType} data to display.
      </div>
    );
  }

  // --- Dynamic Header Generation ---
  const firstUser = users[0] || {};
  
  // Custom mapping for readable headers
  const customKeyMap = {
    // Student Keys
    'rollNo': 'Roll No',
    'idNo': 'ID No',
    'hallTicketNo': 'Hall Ticket',
    
    // Schedule Allotment Keys
    'YEAR': 'Year',
    'SEM': 'Semester',
    'CLASS': 'Class Name',
    'FACULTY': 'Faculty Email',

    // Common Keys
    'name': 'Name',
    'gender': 'Gender',
    'branch': 'Branch',
    'department': 'Department',
    'gmail': 'Email',
    
    // Fallback headers for quick file parsing
    'Col1': 'Col 1 (Header Guess)',
    'Col2': 'Col 2 (Header Guess)',
    'Col3': 'Col 3 (Header Guess)',
    'Col4': 'Col 4 (Header Guess)',
  };
  
  // Logic to determine which headers to show and in what order
  let headerKeys = Object.keys(firstUser);

  // Prioritize keys based on userType
  if (userType === 'Schedule Allotment') {
      // Use the headers generated by the file reader/parser
      headerKeys = Object.keys(firstUser); 
  } else if (userType === 'Student') {
      headerKeys = ['rollNo', 'idNo', 'name', 'gender'].filter(key => headerKeys.includes(key));
  }
  
  // Use all other keys not explicitly listed, ensuring no duplication
  const finalHeaders = Array.from(new Set([...headerKeys, ...Object.keys(firstUser)])).map(key => ({
    key: key, 
    label: customKeyMap[key] || key.charAt(0).toUpperCase() + key.slice(1) // Capitalize if no custom map
  }));


  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="bg-white rounded-xl shadow-lg border border-gray-200 p-6 w-full"
    >
      <h3 className="text-xl font-semibold text-gray-800 mb-4">
        Preview {userType} Data ({users.length} Records)
      </h3>
      <div className="overflow-x-auto rounded-lg border border-gray-300 max-h-[60vh]">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50 sticky top-0">
            <tr>
              {finalHeaders.map(header => (
                <th 
                  key={header.key} 
                  className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider min-w-[120px]"
                >
                  {header.label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {users.map((user, index) => (
              <tr key={index}>
                {finalHeaders.map(header => (
                  <td 
                    key={header.key} 
                    className="px-6 py-4 whitespace-nowrap text-sm text-gray-600"
                  >
                    {user[header.key] || '-'}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      
      <div className="mt-6 flex justify-end space-x-4">
        <button
          onClick={onCancel}
          className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-100 transition-colors"
        >
          Cancel
        </button>
        <button
          onClick={onConfirm}
          className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
        >
          Confirm & Save {userType}
        </button>
      </div>
    </motion.div>
  );
};

export default UserPreviewTable;